CREATE TYPE "AdminStatus" AS ENUM ('PENDING', 'APPROVED', 'SUSPENDED');

CREATE TABLE "MasterAdmin" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "name" TEXT NOT NULL, "loginAttempts" INTEGER NOT NULL DEFAULT 0, "lockedUntil" TIMESTAMP(3), "lastLogin" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "MasterAdmin_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Admin" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "name" TEXT NOT NULL, "phone" TEXT, "status" "AdminStatus" NOT NULL DEFAULT 'PENDING', "emailVerified" BOOLEAN NOT NULL DEFAULT false, "emailVerificationToken" TEXT, "emailVerificationExpiry" TIMESTAMP(3), "passwordResetToken" TEXT, "passwordResetExpiry" TIMESTAMP(3), "loginAttempts" INTEGER NOT NULL DEFAULT 0, "lockedUntil" TIMESTAMP(3), "lastLogin" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "Admin_pkey" PRIMARY KEY ("id"));
CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "name" TEXT NOT NULL, "phone" TEXT, "adminId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'active', "emailVerified" BOOLEAN NOT NULL DEFAULT false, "emailVerificationToken" TEXT, "emailVerificationExpiry" TIMESTAMP(3), "passwordResetToken" TEXT, "passwordResetExpiry" TIMESTAMP(3), "loginAttempts" INTEGER NOT NULL DEFAULT 0, "lockedUntil" TIMESTAMP(3), "lastLogin" TIMESTAMP(3), "profileDetails" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Property" ("id" TEXT NOT NULL, "adminId" TEXT NOT NULL, "name" TEXT NOT NULL, "address" TEXT NOT NULL, "roomNumber" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "Property_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RentalRecord" ("id" TEXT NOT NULL, "adminId" TEXT NOT NULL, "userId" TEXT NOT NULL, "propertyId" TEXT NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3) NOT NULL, "status" TEXT NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "RentalRecord_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Agreement" ("id" TEXT NOT NULL, "adminId" TEXT NOT NULL, "userId" TEXT NOT NULL, "propertyId" TEXT NOT NULL, "rentAmountInfo" DOUBLE PRECISION NOT NULL, "depositAmountInfo" DOUBLE PRECISION NOT NULL, "noticePeriod" TEXT, "lockInPeriod" TEXT, "maintenanceRules" TEXT, "houseRules" TEXT, "termsAndConditions" TEXT, "agreementVersion" INTEGER NOT NULL DEFAULT 1, "status" TEXT NOT NULL DEFAULT 'Draft', "digitalAcceptanceStatus" TEXT NOT NULL DEFAULT 'Pending', "acceptedAt" TIMESTAMP(3), "acceptedIp" TEXT, "acceptedDevice" TEXT, "expiryDate" TIMESTAMP(3), "clauses" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "Agreement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UploadedDocument" ("id" TEXT NOT NULL, "uploaderId" TEXT NOT NULL, "uploaderType" TEXT NOT NULL, "adminId" TEXT, "userId" TEXT, "documentType" TEXT NOT NULL, "originalName" TEXT NOT NULL, "secureFileName" TEXT NOT NULL, "fileUrl" TEXT NOT NULL, "mimeType" TEXT, "fileSize" INTEGER, "status" TEXT NOT NULL DEFAULT 'Uploaded', "rejectionReason" TEXT, "aiSummary" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "UploadedDocument_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UserRequest" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "adminId" TEXT NOT NULL, "category" TEXT, "priority" TEXT, "description" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'Pending', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "UserRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "recipientId" TEXT NOT NULL, "recipientType" TEXT NOT NULL, "adminId" TEXT, "userId" TEXT, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "type" TEXT NOT NULL DEFAULT 'info', "readStatus" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "deletedAt" TIMESTAMP(3), CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL, "actorId" TEXT NOT NULL, "actorType" TEXT NOT NULL, "actorEmail" TEXT, "actorName" TEXT, "action" TEXT NOT NULL, "targetId" TEXT, "targetTable" TEXT, "oldValue" JSONB, "newValue" JSONB, "ipAddress" TEXT, "deviceInfo" TEXT, "status" TEXT NOT NULL DEFAULT 'success', "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LoginActivity" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" TEXT NOT NULL, "email" TEXT NOT NULL, "status" TEXT NOT NULL, "ipAddress" TEXT, "deviceInfo" TEXT, "failedReason" TEXT, "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LoginActivity_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "MasterAdmin_email_key" ON "MasterAdmin"("email");
CREATE UNIQUE INDEX "Admin_email_key" ON "Admin"("email");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

ALTER TABLE "User" ADD CONSTRAINT "User_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "Admin"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Property" ADD CONSTRAINT "Property_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "Admin"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RentalRecord" ADD CONSTRAINT "RentalRecord_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "Admin"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RentalRecord" ADD CONSTRAINT "RentalRecord_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RentalRecord" ADD CONSTRAINT "RentalRecord_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Agreement" ADD CONSTRAINT "Agreement_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "Admin"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Agreement" ADD CONSTRAINT "Agreement_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Agreement" ADD CONSTRAINT "Agreement_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "UploadedDocument" ADD CONSTRAINT "UploadedDocument_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "Admin"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "UploadedDocument" ADD CONSTRAINT "UploadedDocument_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "UserRequest" ADD CONSTRAINT "UserRequest_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "UserRequest" ADD CONSTRAINT "UserRequest_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "Admin"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "Admin"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "LoginActivity" ADD CONSTRAINT "LoginActivity_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
